title: Jan Galinski
description: "A developers logbook"
tagline: A developers logbook

email: jan.galinski@holisticon.de
baseurl: ""
url: "http://jangalinski.github.io"
production_url : http://jangalinski.github.io
twitter_username: jangalinski
github_username:  jangalinski
feedburner_username: jangalinski

# Build settings
markdown: kramdown
highlighter: pygments
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
